version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: backend_db
    restart: always
    environment:
      POSTGRES_USER: myPostgres
      POSTGRES_PASSWORD: "22042004"
      POSTGRES_DB: badafuta
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: backend_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
